version: "3.3"

services:

  app:
    container_name: yssy-sample-api
    build: .
    network_mode: bridge
    ports:
      - 3000:3000
    #env_file: .env

  # db:
  #   container_name: yssy-sample-database
  #   image: postgres:alpine3.14
  #   network_mode: host
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   profiles:
  #     - dev
